import { Inter } from 'next/font/google'
import './globals.css'
import { MyContextProvider } from '@/context/store'
import NavBarComponent from '@/components/navBarComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'COLOR',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <MyContextProvider>
      <body className={inter.className}>{children}</body>
      </MyContextProvider>
    </html>
  )
}
